export const CREATE_CONTENT = 'CREATE_CONTENT';
export const GET_CONTENT = 'GET_CONTENT';
export const GET_ALL_CONTENT = 'GET_ALL_CONTENT';
export const GET_CATEGORY_CONTENT = 'GET_CATEGORY_CONTENT';
export const UPDATE_CONTENT = 'UPDATE_CONTENT';
export const DELETE_CONTENT = 'DELETE_CONTENT';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const FETCH_REQUEST = 'FETCH_REQUEST'

