export const CREATE_RESPONSE = 'CREATE_RESPONSE';
export const GET_RESPONSES = 'GET_RESPONSES';
export const GET_RESPONSE = 'GET_RESPONSE';
export const UPDATE_RESPONSE = 'UPDATE_RESPONSE';
export const DELETE_RESPONSE = 'DELETE_RESPONSE';
export const REQUEST_ERROR = 'REQUEST_ERROR';