export const CREATE_RESPONSE = 'CREATE_RESPONSE';
export const GET_CONTENT_RESPONSE = 'GET_CONTENT_RESPONSE';
export const GET_ALL_RESPONSES = 'GET_ALL_RESPONSES';
export const GET_RESPONSE = 'GET_RESPONSE';
export const UPDATE_RESPONSE = 'UPDATE_RESPONSE';
export const DELETE_RESPONSE = 'DELETE_RESPONSE';
export const FETCH_REQUEST = 'FETCH_REQUEST'
export const REQUEST_ERROR = 'REQUEST_ERROR';